name: Add to Global Board
on:
  issues:
    types: [labeled]
jobs:
  add-to-project:
    if: github.event.label.name == 'ready'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/hossoOG/projects/4
          github-token: ${{ secrets.PROJECT_PAT }}
